In [5]:
# https://phoenixnap.com/kb/install-pip-windows

In [6]:
import numpy as np

In [8]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [9]:
type(a)

numpy.ndarray

In [10]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.transpose(b)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [14]:
b = np.arange(8).reshape(2, 4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
c = b.reshape(2,2,2)

In [16]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [19]:
np.add(a, b)

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [20]:
np.subtract(a,b)

array([[-4, -4, -4],
       [-1, -1, -1],
       [ 2,  2,  2]])

In [21]:
np.multiply(a,b)

array([[ 0,  5, 12],
       [12, 20, 30],
       [24, 35, 48]])

In [22]:
np.divide(a,b)

array([[0.        , 0.2       , 0.33333333],
       [0.75      , 0.8       , 0.83333333],
       [1.5       , 1.4       , 1.33333333]])

In [23]:
s = np.arange(20)

In [24]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
s[:6]

array([0, 1, 2, 3, 4, 5])

In [27]:
d = slice(0,19,5)
s[d]

array([ 0,  5, 10, 15])

In [28]:
for i in np.nditer(s):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [29]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [31]:
np.split(a, [3,5,7])

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]